# pylint: skip-file
# Generated by Django 3.2.7 on 2021-09-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagios_monitor', '0002_auto_20200219_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
