# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-05 18:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagios_monitor', '0003_alter_scheduledevent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
